apiVersion: v1
kind: Service
metadata:
  name: python-app-clusterip-svc
  labels:
    app: python-web-app
spec:
  type: ClusterIP
  selector:
    app: python-web-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
